name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - run: ls -ltr
      - name: install unit test deps
        working-directory: src/webapp/api
        run: npm install
      - name: run unit tests
        working-directory: src/webapp/api
        run: npm run test
        
  