name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install unit test deps
        working-directory: src/webapp/api
        run: npm install
      - name: run unit tests
        working-directory: src/webapp/api
        run: npm run test
      - name: install e2e test deps
        working-directory: e2e/
        run: npm install
      - name: run e2e tests
        working-directory: e2e/
        run: npm run test
        
  